### ISSUE TITLE
update schema for permit and sampling protocol information

### ISSUE THREAD

**Issue by smrgeoinfo** [isamplesorg/metadata#102]
See https://github.com/isamplesorg/isamples_inabox/issues/193

CompliesWith:  one or more statements about the procedures and policies followed in a sample collection event; include biocultural label type content reltating to social conventions and cultural considerations.

AuthorizedBy: one or more statements about legal permits related to accessing a site or removing material from a site. 

use cases from Neil Davies for Fair island work, also Geome permit information.

**Comment by smrgeoinfo** [comment]
current solution is to concatenate this information in the description field. Let's discuss.

**Comment by smrgeoinfo** [comment]
Modeling question:
is PermitInformation on a samplingSite or samplingEvent.     Seems that it should be on the Event, because different agents might sample at the same site, but under different permits....
accessconstraints on the site would say a permit is required, what are conditions of permit, contact xxxx to obtain permit.

**Comment by datadavev** [comment]
Neil indicated that permits are typically "per expedition", with possibly a bundle of permits referenced by samples collected on the expedition, with perhaps some permits not being directly relevant to a particular sample. I think an example might be permits for shore and scuba collection, with a mix collected on the expedition. Assigning a specific permit to each sample during collection appears to be a significant burden.

**Comment by smrgeoinfo** [comment]
looks like 'authorizedBy' and 'compliesWith' have been added to the schema with no documentation, I assume to address this issue?

**Comment by smrgeoinfo** [comment]
these are in schema v1.0 (PR #127)
