### ISSUE TITLE
rename specimen type to materialSampleType

### ISSUE THREAD

**Issue by smrgeoinfo** [isamplesorg/metadata#109]
discussion 2022-09-22 TDGW material sample workgroup
'specimen' has different connotations in some contexts-- implying that there is a preserved object somewhere. Need a more generic term.
proposal for discussion 

1. "Definition: Property to specify the kind of thing the material sample is.'
2. change specimenType to materialSampleType.

this is copy of https://github.com/tdwg/material-sample/issues/26

**Comment by hongcui** [comment]
we agree.
