### ISSUE TITLE
subdivide biome aggregation?

### ISSUE THREAD

**Issue by smrgeoinfo** [isamplesorg/metadata#110]
comment from Chris Meyer 
do we consider all environmental samples as "Biome Aggregations"?
This would include ground up fish guts, filtered water (sterivex filter), ARMS samples, frog swabs, plankton tows, etc.
I'm a little concerned about the difference between aggregated individuals (like a preserved pitfall trap, malaise trap, sieve benthic grab, plankton trap, etc.) vs. a slurried sample where one does not know the contents until downstream omic analyses. Do we differentiate between these two material sample types? (might be important for regulatory issues later as well)

The “Biome aggregation specimen” specimen type vocabulary is currently:

- Physical Specimen <- Any biological specimen <- Biome aggregation specimen

or

- Physical Specimen <- Any aggregation specimen <- Biome aggregation specimen

With the description “Specimen is an aggregation of whole or fragmentary parts of multiple organisms, microscopic or megascopic, representative of some site.”

There are currently no terms in the vocabulary to distinguish a bundle of individuals vs a slurry of individuals. Perhaps there is a need for narrower terms to recognize this distinction. Would two be sufficient? One recognizing a bundle of distinct individuals, the other more like a slurry or cocktail of organisms that are no longer whole?

**Comment by hongcui** [comment]
suggested subterms: bundle biome aggregation for aggregations of individuals, slurry biome aggregation for whole or fragmentary parts. If distinction isn't clear, use upper term biome aggregation.
