### ISSUE TITLE
update document generation to pull from vocabularies repo

### ISSUE THREAD

**Issue by datadavev** [isamplesorg/metadata#144]
The vocabularies have been split out to another repo: https://github.com/isamplesorg/vocabularies

Goal of this issue is to update the metadata documentation generation to use the vocabularies repo as the source for that part of the documentation.

The current metadata docs generation happens through the GH action `build-docs.yml` at the "Parse vocabularies" step which runs `make vocabs`. That build step needs to be updated to either grab markdown from the vocabularies repo or checkout and build with the vocabulary repo directly.

**Comment by smrgeoinfo** [comment]
status?

**Comment by dannymandel** [comment]
This one can be closed. It was implemented a while back.
