### ISSUE TITLE
Design transform mechanism

### ISSUE THREAD

**Issue by datadavev** [isamplesorg/metadata#17]
The goal here is to implement methods that take as input a record from a source collection and transforms the record to produce as output a rendering of the record that conforms with the common model being developed in iSamples.

Repository: https://github.com/isamplesorg/metadata

The transform will probably be written in Python and will have a method signature something like:

```
def transform(source_record: typing.Dict) -> typing.Dict:
    ‘’’identity transform
    ’’’
    result = source_record
    return result
```

There’s a few records in the repository above, plenty more available from the sources and being collated at https://mars.cyverse.org/. The source for pulling the records from the collections is in https://github.com/isamplesorg/isamples_inabox/tree/develop (the develop branch is most up-to-date).

One potential challenge with the SESAR records (actually any JSON-LD records) is that they are technically JSON-LD, which is both JSON and a serialization format for RDF. As such, a reserialization of the content may not present the same structure even though semantically the content is identical. The JSON-LD spec provides an extension for Framing JSON-LD to help ensure a consistent JSON structure.

**Comment by dannymandel** [comment]
Merged this one in https://github.com/isamplesorg/metadata/pull/18

**Comment by dannymandel** [comment]
@datadavev Are you ok with me closing this one or should you?  Not sure what our desired workflow should be with these issues.

**Comment by datadavev** [comment]
Yep, good to close.
