### ISSUE TITLE
Open context test mapping, descriptions

### ISSUE THREAD

**Issue by smrgeoinfo** [isamplesorg/metadata#46]
The mapping of content from the source ('raw') OpenContext JSON descriptions to iSamples descriptions needs some cleanup. 
Use of Descriptions: 
 /description-- this is the description of the sample and properties that don't fit other places
  /producedBy/description -- this is description information related to the sampling event-- sampling procedure, preparations etc.
  /producedBy/samplingSite/description -- this is description information about the sampling site
 
 for instance take metadata/28722/k2d511s24:
I'd expects description content to look like this:
 /description: "'early bce/ce': -700.0 | 'late bce/ce': -535.0 | updated: 2021-06-27T20:49:18Z, 'Consists of': glass | 'Consists of': Cobalt glass | 'Has type': sample | 'Temporal Coverage': Archaic (580 BCE - 482 BCE) | 'Temporal Coverage': Orientalizing (750 BCE - 582 BCE)",   [this is all the info about the sample....]
 
 /producedBy/description: "Poggio Civitate Excavation Project"  [where did this come from in the source JSON?]
 
 /producedBy/samplingSite/description  no information provided  [no real description of the sampling site; would have to delve into the OpenContext links to get this kind of info--e.g. where exactly in a trench or excavation square was this artifact recovered?]

**Comment by qgan7125** [comment]
The text in /producedBy/description comes from the decription in the "project url". I am not sure if we need it. I could delete it. Sorry for checking github issues late.

**Comment by smrgeoinfo** [comment]
I think we can close this. @qgan7125 thoughts?

**Comment by qgan7125** [comment]
Yeah
