### ISSUE TITLE
Draft schema for isamples metadata

### ISSUE THREAD

**Issue by datadavev** [isamplesorg/metadata#7]
Gather examples and develop a draft metadata schema that expresses the required properties.

**Comment by smrgeoinfo** [comment]
see initial [draft model (UML) from SMR](https://github.com/isamplesorg/metadata/blob/main/DraftSamplingModel20210208.png) and [digital specimen model](https://github.com/isamplesorg/metadata/blob/main/DigitalSpecimenModel.png) and  for discussion

**Comment by smrgeoinfo** [comment]
Several draft vocabularies have been gathered related to objectType/specimenType and material.  , in the [vocabulary folder ](https://github.com/isamplesorg/metadata/tree/main/vocabulary)on github.

**Comment by smrgeoinfo** [comment]
close for now, work on more specific issues
