### ISSUE TITLE
LinkML team recommendation

### ISSUE THREAD

**Issue by qgan7125** [isamplesorg/metadata#93]
After I register the iSamples schema for linkML, they have two recommendations.
1) not putting versions in the iSamples schema.
2) make a schema homepage as "https://isamplesorg.github.io/metadata". Our current one is "https://github.com/isamplesorg/metadata".

**Comment by smrgeoinfo** [comment]
https://isamplesorg.github.io/metadata is implemented and live. 
I don't see the reason for not haveing a version in the yaml doc, and it seems like a good thing to me. 
I think we can close this one.
